
[functions.delete_user]
enabled = true
verify_jwt = true
import_map = "./functions/delete_user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete_user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete_user/*.html" ]

[functions.username_login]
enabled = true
verify_jwt = false
import_map = "./functions/username_login/deno.json"
entrypoint = "./functions/username_login/index.ts"

[functions.admin_user_status]
enabled = true
verify_jwt = true
import_map = "./functions/admin_user_status/deno.json"
entrypoint = "./functions/admin_user_status/index.ts"
