-- Simple guestbook with one reply level and reversible moderation.

create table if not exists public.guestbook_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  author_name text not null,
  parent_id bigint references public.guestbook_entries(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now(),
  is_hidden boolean not null default false,
  hidden_at timestamptz,
  hidden_by uuid references auth.users(id) on delete set null,
  constraint guestbook_message_length check (char_length(btrim(message)) between 1 and 1000)
);

create index if not exists guestbook_entries_created_at_idx
  on public.guestbook_entries (created_at desc);
create index if not exists guestbook_entries_parent_id_idx
  on public.guestbook_entries (parent_id);

alter table public.guestbook_entries enable row level security;
revoke all on table public.guestbook_entries from anon, authenticated;

create or replace function public.can_moderate_guestbook()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid()
      and role in ('admin', 'moderator')
  );
$$;

create or replace function public.list_guestbook_entries(include_hidden boolean default false)
returns table (
  id bigint,
  parent_id bigint,
  author_name text,
  message text,
  created_at timestamptz,
  is_hidden boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if include_hidden and not public.can_moderate_guestbook() then
    raise exception 'moderator_required' using errcode = '42501';
  end if;

  return query
  select
    entry.id,
    entry.parent_id,
    coalesce(profile.username, entry.author_name),
    entry.message,
    entry.created_at,
    entry.is_hidden
  from public.guestbook_entries as entry
  left join public.guestbook_entries as parent on parent.id = entry.parent_id
  left join public.profiles as profile on profile.user_id = entry.user_id
  where include_hidden
    or (
      not entry.is_hidden
      and (entry.parent_id is null or not coalesce(parent.is_hidden, true))
    )
  order by entry.created_at desc
  limit 500;
end;
$$;

create or replace function public.create_guestbook_entry(entry_message text, reply_to bigint default null)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  cleaned_message text := btrim(entry_message);
  current_username text;
  new_entry_id bigint;
begin
  if current_user_id is null then
    raise exception 'login_required' using errcode = '42501';
  end if;

  if exists (
    select 1 from auth.users
    where id = current_user_id and banned_until > now()
  ) then
    raise exception 'account_suspended' using errcode = '42501';
  end if;

  if cleaned_message is null or char_length(cleaned_message) not between 1 and 1000 then
    raise exception 'invalid_message' using errcode = '22023';
  end if;

  select username into current_username
  from public.profiles
  where user_id = current_user_id;

  if current_username is null or btrim(current_username) = '' then
    raise exception 'profile_required' using errcode = '42501';
  end if;

  if exists (
    select 1 from public.guestbook_entries
    where user_id = current_user_id
      and created_at > now() - interval '20 seconds'
  ) then
    raise exception 'posting_too_fast' using errcode = 'P0001';
  end if;

  if reply_to is not null and not exists (
    select 1 from public.guestbook_entries
    where id = reply_to
      and parent_id is null
      and not is_hidden
  ) then
    raise exception 'invalid_parent' using errcode = '23503';
  end if;

  insert into public.guestbook_entries (user_id, author_name, parent_id, message)
  values (current_user_id, btrim(current_username), reply_to, cleaned_message)
  returning id into new_entry_id;

  return new_entry_id;
end;
$$;

create or replace function public.set_guestbook_entry_hidden(target_entry_id bigint, hidden boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.can_moderate_guestbook() then
    raise exception 'moderator_required' using errcode = '42501';
  end if;

  update public.guestbook_entries
  set
    is_hidden = hidden,
    hidden_at = case when hidden then now() else null end,
    hidden_by = case when hidden then auth.uid() else null end
  where id = target_entry_id;

  if not found then
    raise exception 'entry_not_found' using errcode = 'P0002';
  end if;

  return true;
end;
$$;

revoke all on function public.can_moderate_guestbook() from public, anon, authenticated;
revoke all on function public.list_guestbook_entries(boolean) from public, anon, authenticated;
revoke all on function public.create_guestbook_entry(text, bigint) from public, anon, authenticated;
revoke all on function public.set_guestbook_entry_hidden(bigint, boolean) from public, anon, authenticated;

grant execute on function public.can_moderate_guestbook() to authenticated;
grant execute on function public.list_guestbook_entries(boolean) to anon, authenticated;
grant execute on function public.create_guestbook_entry(text, bigint) to authenticated;
grant execute on function public.set_guestbook_entry_hidden(bigint, boolean) to authenticated;

comment on table public.guestbook_entries is
  'Guestbook posts and one-level replies. Moderation is reversible through is_hidden.';
